apiVersion: 1

datasources:
  - name: MyPrometheusDataSource
    type: prometheus
    access: proxy
    url: http://prometheus-server:9090
    jsonData:
      timeInterval: "5s"
    secureJsonData:
      basicAuth: false
    version: 1
    editable: true