FROM docker.io/grafana

COPY ./container_setup/grafana/datasources.yaml /etc/grafana/provisioning/datasources/datasources.yaml
COPY ./container_setup/grafana/dashboards.yaml /etc/grafana/provisioning/dashboards/dashboards.yaml
